### ISSUE TITLE
Latest ubuntu is broken (hirsute hippo)

### ISSUE THREAD

**Issue by xloem** [neurodebian/neurodebian#82]
I just installed ubuntu 21.04 and its neurodebian package, but `apt-get update` gives
```
Err:7 http://neuro.debian.net/debian hirsute Release
  404  Not Found [IP: 129.170.233.11 80]
```

**Comment by yarikoptic** [comment]
Eh, time goes. I guess we missed yet another Ubuntu release ;-) I will look into populating it asap. Thank you for the report

**Comment by xloem** [comment]
I am finding `hirsute hippo` now =)  now I'm getting "doesn't support architecture 'arm64'" .  Does neurodebian support arm64?

**Comment by yarikoptic** [comment]
Thank you @xloem for floating this issue up in my mail box! ;) 

- unfortunately we indeed do not "support" arm64 ATM, in that we are not building backports for that architecture for any package

Protocol of what I have done (so I could remember later since this knowledge seems to be getting displaced with other bits):
- I have now added hirsute to the configs (6f149416f25ab3f0ff7fe3991e6f202aef63acb9), actual APT repo on neuro.debian.net reprepro for both main and devel, started to build cow chroots to build packages (so more todo there -- actually may be do rebuild some packages),
- submitted PR to get official docker images for nd21.04: https://github.com/docker-library/official-images/pull/10443

**Comment by yarikoptic** [comment]
with that I close this issue, it should not longer be "broken" for architectures we support (primarily i386  and amd64 and some sprinkles of other archs builds). rebuilt existing packages might appear in the archive for the hirsute soonish.
